import { useState, useEffect } from "react";

const C = { bg:"#000000", card:"rgba(18,18,17,0.72)", cardH:"rgba(30,28,24,0.85)", bdr:"rgba(255,198,85,0.10)", bdrH:"rgba(255,198,85,0.28)", gold:"#FFC655", goldD:"#E0AC44", goldM:"#AE8E51", t1:"#FFFFFF", t2:"rgba(255,255,255,0.55)", t3:"rgba(255,255,255,0.30)", mercury:"#E5E5E5" };
const MT = { INVESTOR:"#4ADE80", ADVISORY:"#FF6B6B", STRATEGY:"#FB923C" };
const BT = { "CASE STUDY":"#FFC655", LEADERSHIP:"#A78BFA", "MARKET INTEL":"#4ADE80", GOVERNANCE:"#60A5FA", BRAND:"#FB923C", PARTNERSHIP:"#22D3EE" };
const MEETINGS=[{id:1,type:"INVESTOR",date:"Apr 9",title:"Mark Shirman Investor Discovery Call",summary:"Discovery call with Mark Shirman, former CEO of RiverMeadow Software (connection via Jeff Newman). Strong investment interest expressed.",org:"BizAnalytica"},{id:2,type:"INVESTOR",date:"Apr 7",title:"Scott Price Investor Discovery Call",summary:"Discovery call with Scott Price, President at Beacon Oral Specialists (via Tom Castillo). Personal investment interest discussed.",org:"Beacon Oral"},{id:3,type:"ADVISORY",date:"Apr 2",title:"Edwin Prather IAB Discovery Call",summary:"Discovery call with Edwin Prather, Bay Area attorney and General Counsel at Alexander's Steakhouse.",org:"Prather"},{id:4,type:"INVESTOR",date:"Apr 2",title:"Kris Withrow — Fenwick & West",summary:"Strategic legal framework and investor introduction opportunities.",org:"Fenwick"},{id:5,type:"STRATEGY",date:"Apr 2",title:"TrackMan Momentum Call — Adam Katz",summary:"Integration possibilities and data partnership alignment for the platform.",org:"TrackMan"},{id:6,type:"ADVISORY",date:"Apr 2",title:"Stephen Piscotty IAB Discovery Call",summary:"IAB candidacy — former MLB experience and player development connections.",org:"Piscotty"},{id:7,type:"INVESTOR",date:"Mar 28",title:"Tom Castillo Follow-Up",summary:"Investment terms, timeline, and next steps for formalizing commitment.",org:"Castillo"},{id:8,type:"STRATEGY",date:"Mar 25",title:"ACIS Positioning Review",summary:"ACIS positioning vs. NFL Digital Athlete and NBA Second Spectrum comparables.",org:"Internal"}];
const BUZZ=[{id:1,type:"CASE STUDY",title:"Hayden Birdsong Case Study",author:"Chase Spivey",date:"Apr 14",desc:"Deep-dive on SF Giants pitcher Hayden Birdsong's biomechanical markers through the ACIS lens. Demonstrates predictive injury detection with real MLB data — cornerstone proof-of-concept for investor conversations."},{id:2,type:"LEADERSHIP",title:"Sheldon's Power Statement",author:"Sheldon McClelland",date:"Apr 11",desc:"COO's definitive positioning statement on Baseline Analytics' market authority and competitive moat. Articulates the 'why now' and 'why us' for external-facing communications."},{id:3,type:"MARKET INTEL",title:"Marketplace Comparables Doc",author:"Sheldon McClelland",date:"Apr 8",desc:"League-wide sports tech deal comparables — $6B+ in documented transactions across MLB, NBA, NFL. Positions ACIS pricing against BAMTech, Digital Athlete, Second Spectrum."},{id:4,type:"GOVERNANCE",title:"IAB Program Framework Finalized",author:"Jeff Newman",date:"Apr 5",desc:"Advisory Board governance completed — roles, seat terms, honorarium structure, quarterly cadence."},{id:5,type:"BRAND",title:"Brand Guidelines v1.0 Delivered",author:"PERKK Studio",date:"Apr 3",desc:"Full identity system — logo lockups, color palette, typography, brand asset patterns, mockups."},{id:6,type:"PARTNERSHIP",title:"TrackMan Integration Pathway",author:"Chase Spivey",date:"Mar 30",desc:"Technical alignment confirmed with TrackMan for data feed integration within ACIS."}];
const DOCS=[{name:"Sports Tech Deal Comparables",ext:"PDF",pages:"5 pg",date:"Mar '26",cat:"Intel"},{name:"IAB Overview & Governance",ext:"PDF",pages:"3 pg",date:"Mar '26",cat:"Gov"},{name:"Brand Guidelines v1.0",ext:"PDF",pages:"42 pg",date:"Jan '26",cat:"Brand"},{name:"Hayden Birdsong Case Study",ext:"DOC",pages:"Draft",date:"Apr '26",cat:"Case"},{name:"Investor Deck — Q1 2026",ext:"PPTX",pages:"18 sl",date:"Apr '26",cat:"Deck"},{name:"Power Statement — McClelland",ext:"DOC",pages:"1 pg",date:"Apr '26",cat:"Lead"}];
const QS=["How many investor meetings this month?","Latest on IAB onboarding?","Summarize the Birdsong case study","Deal comparables overview","Materials created this cycle?","Next advisory board call?"];
const ANS={"How many investor meetings this month?":"4 investor meetings in April 2026 — Mark Shirman (BizAnalytica), Scott Price (Beacon Oral), Kris Withrow (Fenwick & West), and Tom Castillo follow-up.","Latest on IAB onboarding?":"Framework finalized. Two April discovery calls — Edwin Prather and Stephen Piscotty. Both expressed strong interest.","Summarize the Birdsong case study":"Analysis of SF Giants pitcher Birdsong's biomechanical markers through ACIS. Demonstrates real-world predictive injury detection using MLB data. Cornerstone proof-of-concept.","Deal comparables overview":"7 deals totaling $6B+. NFL Digital Athlete ($60M+), Second Spectrum + NBA (~$42M/yr), Sportradar + MLB ($37M equity + annual). ACIS range: $15–50M/yr.","Materials created this cycle?":"Birdsong Case Study (Chase), Power Statement (Sheldon), Comparables Doc (Sheldon), IAB Framework (Jeff), Brand Guidelines (PERKK), TrackMan memo (Chase).","Next advisory board call?":"No date confirmed. IAB set for 4 quarterly meetings/year. Next window: late April / early May 2026."};
const CTX=`You are the Baseline Analytics Stakeholder Portal assistant. 2-3 sentences, use names/dates/numbers.\nMEETINGS: ${MEETINGS.map(m=>`${m.date}: ${m.title}`).join("|")}\nBUZZ: ${BUZZ.map(b=>`${b.date}: ${b.title} by ${b.author}`).join("|")}\nKEY: CEO Chase Spivey, COO Sheldon McClelland, Chairman Jeff Newman. ACIS=AI injury prevention for MLB. Comps: $6B+, ACIS $15-50M/yr.`;
const CY="Mar 24 – Apr 23, 2026";

function Logo({s=28}){return <svg width={s*.75} height={s} viewBox="0 0 30 40" fill="none"><rect x="2" y="0" width="2.2" height="28" rx="1" fill={C.goldM}/><rect x="7" y="4" width="2.2" height="24" rx="1" fill={C.gold}/><rect x="12" y="0" width="2.2" height="32" rx="1" fill={C.gold}/><rect x="17" y="6" width="2.2" height="22" rx="1" fill={C.gold}/><rect x="22" y="2" width="2.2" height="26" rx="1" fill={C.goldM}/><path d="M13 32 L8 40 L18 40 Z" fill={C.goldD} opacity="0.45"/></svg>}
function Lines({h=180,o=0.06}){const l=[];for(let i=0;i<45;i++){const x=8+i*22,len=25+Math.random()*(h-50),y=Math.random()*(h-len);l.push(<line key={i} x1={x} y1={y} x2={x} y2={y+len} stroke={Math.random()>.5?C.gold:C.t1} strokeWidth={1.2+Math.random()} opacity={o*(.35+Math.random()*.65)}/>)}return <svg width="100%" height={h} style={{position:"absolute",top:0,left:0,pointerEvents:"none"}}>{l}</svg>}
function Badge({label,color}){return <span style={{display:"inline-flex",alignItems:"center",gap:5,padding:"3px 10px",borderRadius:20,border:`1px solid ${color}33`,background:`${color}12`,fontSize:10,fontWeight:600,letterSpacing:"0.07em",color,textTransform:"uppercase",whiteSpace:"nowrap"}}><span style={{width:5,height:5,borderRadius:"50%",background:color,flexShrink:0}}/>{label}</span>}
function Card({children,style,onClick,gold}){const[h,setH]=useState(false);return (<div onClick={onClick} onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{background:h?C.cardH:C.card,border:`1px solid ${h?C.bdrH:gold?`${C.gold}20`:C.bdr}`,borderRadius:14,padding:24,backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",transition:"all 0.3s ease",cursor:onClick?"pointer":"default",position:"relative",overflow:"hidden",...style}}>{gold&&<div style={{position:"absolute",top:0,left:0,right:0,height:2,background:`linear-gradient(90deg,${C.gold},${C.goldD},transparent)`}}/>}{children}</div>)}

export default function V1(){
  const[nav,setNav]=useState("overview");const[filter,setFilter]=useState("ALL");const[exp,setExp]=useState(null);const[q,setQ]=useState("");const[a,setA]=useState("");const[loading,setLoading]=useState(false);const[input,setInput]=useState("");const[hist,setHist]=useState([]);const[fade,setFade]=useState(false);const[cyc,setCyc]=useState(false);
  useEffect(()=>{setTimeout(()=>setFade(true),80)},[]);
  const fm=filter==="ALL"?MEETINGS:MEETINGS.filter(m=>m.type===filter);
  const ask=async(question)=>{setQ(question);setA("");setLoading(true);const msgs=[...hist,{role:"user",content:question}];if(ANS[question]){setA(ANS[question]);setHist([...msgs,{role:"assistant",content:ANS[question]}]);setLoading(false);return}try{const r=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:"claude-sonnet-4-20250514",max_tokens:1000,system:CTX,messages:msgs.slice(-6)})});const d=await r.json();const ans=d.content?.map(b=>b.type==="text"?b.text:"").filter(Boolean).join("\n")||"No response.";setA(ans);setHist([...msgs,{role:"assistant",content:ans}])}catch{setA("Connection error.")}setLoading(false)};
  const submit=()=>{if(input.trim()){ask(input.trim());setInput("")}};
  return(
    <div style={{fontFamily:"'Manrope',sans-serif",background:C.bg,minHeight:"100vh",color:C.t1,opacity:fade?1:0,transition:"opacity 0.7s ease"}}>
      <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet"/>
      <style>{`*{box-sizing:border-box}::-webkit-scrollbar{width:6px}::-webkit-scrollbar-thumb{background:${C.gold}30;border-radius:3px}@keyframes pulse{0%,100%{opacity:.3}50%{opacity:1}}`}</style>
      {/* NAV */}
      <nav style={{position:"sticky",top:0,zIndex:100,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"14px 28px",borderBottom:`1px solid ${C.bdr}`,backdropFilter:"blur(24px)",background:"rgba(0,0,0,0.78)"}}>
        <div style={{display:"flex",alignItems:"center",gap:12}}><Logo s={30}/><div><div style={{fontSize:13,fontWeight:700,letterSpacing:"0.11em",textTransform:"uppercase"}}><span>Baseline</span><span style={{color:C.t2,fontWeight:400,marginLeft:5}}>Analytics</span></div><div style={{fontSize:9,color:C.goldM,letterSpacing:"0.08em",marginTop:1}}>STAKEHOLDER PORTAL</div></div></div>
        <div style={{display:"flex",gap:3}}>{["overview","buzz","meetings","vault","ask"].map(n=><button key={n} onClick={()=>setNav(n)} style={{background:nav===n?`${C.gold}15`:"transparent",border:nav===n?`1px solid ${C.gold}30`:"1px solid transparent",color:nav===n?C.gold:C.t2,padding:"5px 14px",borderRadius:20,fontSize:11,fontWeight:600,letterSpacing:"0.06em",textTransform:"uppercase",cursor:"pointer",fontFamily:"inherit"}}>{n}</button>)}</div>
        <div style={{fontSize:10,color:C.t3,textAlign:"right"}}><div>Updated: Apr 23, 2026</div><div style={{color:C.goldM,fontSize:9,marginTop:1}}>Cycle: {CY}</div></div>
      </nav>
      <div style={{maxWidth:1240,margin:"0 auto",padding:"28px 28px 72px"}}>
        {/* OVERVIEW */}
        {nav==="overview"&&<><div style={{position:"relative",marginBottom:40,paddingBottom:12}}><Lines h={160} o={0.05}/><div style={{position:"relative",zIndex:1,paddingTop:16}}><h1 style={{fontSize:48,fontWeight:200,lineHeight:1.12,margin:0,letterSpacing:"-0.03em"}}>Stakeholder<br/><span style={{color:C.gold,fontWeight:300}}>Portal.</span></h1><p style={{fontSize:14,color:C.t2,marginTop:12,fontWeight:300}}>{CY}</p></div></div>
          {/* Buzz */}
          <div style={{marginBottom:44}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><span style={{fontSize:10,fontWeight:600,letterSpacing:"0.13em",color:C.gold,textTransform:"uppercase",padding:"4px 12px",border:`1px solid ${C.gold}30`,borderRadius:20,background:`${C.gold}08`}}>RECENT BUZZ · 30-DAY CYCLE</span><button onClick={()=>setCyc(!cyc)} style={{background:"transparent",border:`1px solid ${C.bdr}`,color:C.t2,padding:"3px 10px",borderRadius:20,fontSize:9,cursor:"pointer",fontFamily:"inherit"}}>{cyc?"HIDE":"CYCLE INFO"}</button></div>
            {cyc&&<Card style={{marginBottom:16,padding:14,background:`${C.gold}06`,border:`1px solid ${C.gold}18`}}><p style={{fontSize:12,color:C.t2,margin:0,lineHeight:1.7}}>Updates on a <span style={{color:C.t1}}>30-day cycle</span>. All items <span style={{color:C.gold}}>erased and replaced</span> each period. Current: <span style={{color:C.t1}}>{CY}</span>.</p></Card>}
            <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14}}>{BUZZ.slice(0,3).map(b=><Card key={b.id} gold onClick={()=>setExp(exp===b.id?null:b.id)}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><Badge label={b.type} color={BT[b.type]}/><span style={{fontSize:10,color:C.t3}}>{b.date}</span></div><div style={{fontSize:9,color:C.goldM,fontWeight:600,marginBottom:3}}>📌 {b.author}</div><h3 style={{fontSize:15,fontWeight:600,margin:"0 0 8px",lineHeight:1.3}}>{b.title}</h3><p style={{fontSize:12,color:C.t2,margin:0,lineHeight:1.6,display:"-webkit-box",WebkitLineClamp:exp===b.id?20:3,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{b.desc}</p></Card>)}</div>
            <div style={{textAlign:"center",marginTop:18}}><button onClick={()=>setNav("buzz")} style={{background:`${C.gold}10`,border:`1px solid ${C.gold}30`,color:C.gold,padding:"9px 24px",borderRadius:24,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:"inherit"}}>VIEW ALL BUZZ →</button></div>
          </div>
          {/* Ask preview */}
          <Card style={{marginBottom:44,padding:24}}><div style={{fontSize:10,fontWeight:600,letterSpacing:"0.12em",color:C.gold,marginBottom:10}}>💬 ASK THE PORTAL</div><div style={{fontSize:20,fontWeight:300,marginBottom:14}}>Search portal data.</div><div style={{display:"flex",flexWrap:"wrap",gap:7}}>{QS.slice(0,4).map((qu,i)=><button key={i} onClick={()=>{setNav("ask");ask(qu)}} style={{background:`${C.t1}06`,border:`1px solid ${C.bdr}`,color:C.t2,padding:"7px 14px",borderRadius:20,fontSize:11,cursor:"pointer",fontFamily:"inherit"}}>{qu}</button>)}</div></Card>
          {/* Meetings */}
          <div><div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline",marginBottom:16}}><span style={{fontSize:10,fontWeight:600,letterSpacing:"0.13em",color:C.gold,textTransform:"uppercase",padding:"4px 12px",border:`1px solid ${C.gold}30`,borderRadius:20,background:`${C.gold}08`}}>TIMELINE</span><div><span style={{fontSize:34,fontWeight:700,color:C.gold}}>{MEETINGS.length}</span><span style={{fontSize:11,color:C.t2,marginLeft:6,fontWeight:600,letterSpacing:"0.1em",textTransform:"uppercase"}}>meetings</span></div></div>
            <div style={{display:"flex",gap:6,marginBottom:18}}>{["ALL","INVESTOR","ADVISORY","STRATEGY"].map(f=><button key={f} onClick={()=>setFilter(f)} style={{background:filter===f?`${C.gold}15`:"transparent",border:filter===f?`1px solid ${C.gold}30`:`1px solid ${C.bdr}`,color:filter===f?C.gold:C.t2,padding:"4px 12px",borderRadius:20,fontSize:11,fontWeight:500,cursor:"pointer",fontFamily:"inherit"}}>{f}</button>)}</div>
            <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14}}>{fm.slice(0,6).map(m=><Card key={m.id}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><Badge label={m.type} color={MT[m.type]}/><span style={{fontSize:10,color:C.t3}}>{m.date}</span></div><h3 style={{fontSize:15,fontWeight:600,margin:"0 0 8px",lineHeight:1.3}}>{m.title}</h3><p style={{fontSize:12,color:C.t2,margin:"0 0 14px",lineHeight:1.6,display:"-webkit-box",WebkitLineClamp:3,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{m.summary}</p><div style={{display:"flex",alignItems:"center",gap:7,borderTop:`1px solid ${C.bdr}`,paddingTop:10}}><div style={{width:26,height:26,borderRadius:"50%",background:`${C.gold}15`,border:`1px solid ${C.gold}30`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,color:C.gold,fontWeight:700}}>{m.org.charAt(0)}</div><span style={{fontSize:11,color:C.t2}}>{m.org}</span></div></Card>)}</div>
          </div>
        </>}
        {/* BUZZ */}
        {nav==="buzz"&&<div><div style={{position:"relative",marginBottom:40,paddingBottom:12}}><Lines h={160} o={0.05}/><div style={{position:"relative",zIndex:1,paddingTop:16}}><h1 style={{fontSize:48,fontWeight:200,margin:0}}>Recent<br/><span style={{color:C.gold,fontWeight:300}}>Buzz.</span></h1><p style={{fontSize:14,color:C.t2,marginTop:12,fontWeight:300}}>{CY} — All items reset on cycle end.</p></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:18}}>{BUZZ.map(b=><Card key={b.id} gold={b.id<=3} onClick={()=>setExp(exp===b.id?null:b.id)}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><Badge label={b.type} color={BT[b.type]}/><span style={{fontSize:10,color:C.t3}}>{b.date}</span></div><div style={{fontSize:10,color:C.goldM,marginBottom:5}}>by {b.author}</div><h3 style={{fontSize:17,fontWeight:600,margin:"0 0 10px",lineHeight:1.3}}>{b.title}</h3><p style={{fontSize:12.5,color:C.t2,margin:0,lineHeight:1.7,maxHeight:exp===b.id?"none":55,overflow:"hidden"}}>{b.desc}</p><div style={{fontSize:9,color:C.gold,marginTop:10,fontWeight:600}}>{exp===b.id?"▲ Collapse":"▼ Read more"}</div></Card>)}</div></div>}
        {/* MEETINGS */}
        {nav==="meetings"&&<div><div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline",marginBottom:16}}><h2 style={{fontSize:30,fontWeight:300}}>Meetings.</h2><div style={{display:"flex",gap:6}}>{["ALL","INVESTOR","ADVISORY","STRATEGY"].map(f=><button key={f} onClick={()=>setFilter(f)} style={{background:filter===f?`${C.gold}15`:"transparent",border:filter===f?`1px solid ${C.gold}30`:`1px solid ${C.bdr}`,color:filter===f?C.gold:C.t2,padding:"4px 12px",borderRadius:20,fontSize:11,cursor:"pointer",fontFamily:"inherit"}}>{f}</button>)}</div></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14}}>{fm.map(m=><Card key={m.id}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><Badge label={m.type} color={MT[m.type]}/><span style={{fontSize:10,color:C.t3}}>{m.date}</span></div><h3 style={{fontSize:15,fontWeight:600,margin:"0 0 8px",lineHeight:1.3}}>{m.title}</h3><p style={{fontSize:12,color:C.t2,margin:"0 0 14px",lineHeight:1.6,display:"-webkit-box",WebkitLineClamp:3,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{m.summary}</p><div style={{display:"flex",alignItems:"center",gap:7,borderTop:`1px solid ${C.bdr}`,paddingTop:10}}><div style={{width:26,height:26,borderRadius:"50%",background:`${C.gold}15`,border:`1px solid ${C.gold}30`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,color:C.gold,fontWeight:700}}>{m.org.charAt(0)}</div><span style={{fontSize:11,color:C.t2}}>{m.org}</span></div></Card>)}</div></div>}
        {/* VAULT */}
        {nav==="vault"&&<div><h2 style={{fontSize:30,fontWeight:300,marginBottom:20}}>Documents.</h2>{DOCS.map((d,i)=><Card key={i} style={{padding:18,display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:10}}><div style={{display:"flex",alignItems:"center",gap:14}}><div style={{width:42,height:42,borderRadius:10,background:`${C.gold}10`,border:`1px solid ${C.gold}20`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:700,color:C.gold}}>{d.ext}</div><div><div style={{fontSize:14,fontWeight:600}}>{d.name}</div><div style={{fontSize:11,color:C.t2,marginTop:2}}>{d.cat} · {d.pages} · {d.date}</div></div></div><button style={{background:`${C.t1}06`,border:`1px solid ${C.bdr}`,color:C.t2,padding:"5px 14px",borderRadius:20,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:"inherit"}}>VIEW</button></Card>)}</div>}
        {/* ASK */}
        {nav==="ask"&&<div><div style={{position:"relative",marginBottom:28}}><Lines h={110} o={0.04}/><div style={{position:"relative",zIndex:1}}><h1 style={{fontSize:40,fontWeight:200,margin:0}}>Ask the <span style={{color:C.gold,fontWeight:300}}>Portal.</span></h1><p style={{fontSize:13,color:C.t2,marginTop:8,fontWeight:300}}>Type a question or select one below.</p></div></div>
          <div style={{display:"flex",gap:10,marginBottom:20}}><input type="text" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder="Ask anything about meetings, documents, strategy..." style={{flex:1,padding:"14px 20px",background:`${C.t1}06`,border:`1px solid ${C.bdr}`,borderRadius:14,color:C.t1,fontSize:14,fontFamily:"inherit",outline:"none"}} onFocus={e=>e.target.style.borderColor=`${C.gold}50`} onBlur={e=>e.target.style.borderColor=C.bdr}/><button onClick={submit} disabled={!input.trim()||loading} style={{background:input.trim()?C.gold:`${C.gold}20`,border:"none",color:input.trim()?C.bg:C.t3,padding:"14px 24px",borderRadius:14,fontSize:13,fontWeight:700,cursor:input.trim()?"pointer":"default",fontFamily:"inherit"}}>{loading?"···":"ASK →"}</button></div>
          <div style={{display:"flex",flexWrap:"wrap",gap:8,marginBottom:24}}>{QS.map((qu,i)=><button key={i} onClick={()=>ask(qu)} style={{background:q===qu?`${C.gold}15`:`${C.t1}05`,border:q===qu?`1px solid ${C.gold}40`:`1px solid ${C.bdr}`,color:q===qu?C.gold:C.t2,padding:"9px 18px",borderRadius:22,fontSize:12,cursor:"pointer",fontFamily:"inherit",fontWeight:500}}>{qu}</button>)}</div>
          {loading&&<Card style={{padding:24}}><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{color:C.gold,animation:"pulse 1s infinite"}}>●</span><span style={{fontSize:13,color:C.t2}}>Searching portal data...</span></div></Card>}
          {a&&!loading&&<Card style={{padding:24,border:`1px solid ${C.gold}20`}}><div style={{fontSize:9,fontWeight:600,letterSpacing:"0.1em",color:C.gold,marginBottom:6,textTransform:"uppercase"}}>↳ {q}</div><p style={{fontSize:14,color:C.mercury,margin:0,lineHeight:1.8,fontWeight:300,whiteSpace:"pre-wrap"}}>{a}</p></Card>}
          {!a&&!loading&&<p style={{fontSize:13,color:C.t3,fontStyle:"italic"}}>Select a question or type your own above.</p>}
        </div>}
      </div>
      <div style={{borderTop:`1px solid ${C.bdr}`,padding:"16px 28px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:8}}><Logo s={18}/><span style={{fontSize:10,color:C.t3}}>BASELINE ANALYTICS™ · STAKEHOLDER PORTAL · CONFIDENTIAL</span></div><span style={{fontSize:9,color:C.t3}}>© Baseline Analytics 2026</span></div>
    </div>
  );
}
