import { useState, useEffect } from "react";

const C = { bg:"#FAFAF7", white:"#FFFFFF", surface:"#F4F3EF", border:"rgba(0,0,0,0.06)", borderS:"rgba(0,0,0,0.10)", gold:"#D4A038", goldL:"#F5E6C8", goldBg:"#FBF6EC", goldD:"#B8882E", text:"#1A1A18", t2:"#6B6960", t3:"#A8A49A", t4:"#D0CEC8", shadow:"0 1px 3px rgba(0,0,0,0.04),0 4px 12px rgba(0,0,0,0.03)", shadowH:"0 2px 8px rgba(0,0,0,0.06),0 8px 24px rgba(0,0,0,0.05)" };
const TC = { INVESTOR:"#2D8A56", ADVISORY:"#C0392B", STRATEGY:"#D4760A", "CASE STUDY":"#B8882E", LEADERSHIP:"#7B5EA7", "MARKET INTEL":"#2D8A56", GOVERNANCE:"#3A7BD5", BRAND:"#D4760A", PARTNERSHIP:"#1A8A8A" };
const MEETINGS=[{id:1,type:"INVESTOR",date:"Apr 9",title:"Mark Shirman Investor Discovery Call",summary:"Discovery call with Mark Shirman, former CEO of RiverMeadow Software (connection via Jeff Newman). Strong investment interest expressed.",org:"BizAnalytica"},{id:2,type:"INVESTOR",date:"Apr 7",title:"Scott Price Investor Discovery Call",summary:"Discovery call with Scott Price, President at Beacon Oral Specialists (via Tom Castillo). Personal investment interest discussed.",org:"Beacon Oral"},{id:3,type:"ADVISORY",date:"Apr 2",title:"Edwin Prather IAB Discovery Call",summary:"Discovery call with Edwin Prather, Bay Area attorney and General Counsel at Alexander's Steakhouse.",org:"Prather"},{id:4,type:"INVESTOR",date:"Apr 2",title:"Kris Withrow — Fenwick & West",summary:"Strategic legal framework and investor introduction opportunities.",org:"Fenwick"},{id:5,type:"STRATEGY",date:"Apr 2",title:"TrackMan Momentum Call — Adam Katz",summary:"Integration possibilities and data partnership alignment for the platform.",org:"TrackMan"},{id:6,type:"ADVISORY",date:"Apr 2",title:"Stephen Piscotty IAB Discovery Call",summary:"IAB candidacy — former MLB experience and player development connections.",org:"Piscotty"},{id:7,type:"INVESTOR",date:"Mar 28",title:"Tom Castillo Follow-Up",summary:"Investment terms, timeline, and next steps for formalizing commitment.",org:"Castillo"},{id:8,type:"STRATEGY",date:"Mar 25",title:"ACIS Positioning Review",summary:"ACIS positioning vs. NFL Digital Athlete and NBA Second Spectrum comparables.",org:"Internal"}];
const BUZZ=[{id:1,type:"CASE STUDY",title:"Hayden Birdsong Case Study",author:"Chase Spivey",date:"Apr 14",desc:"Deep-dive on SF Giants pitcher Hayden Birdsong's biomechanical markers through the ACIS lens. Demonstrates predictive injury detection with real MLB data — cornerstone proof-of-concept for investor conversations."},{id:2,type:"LEADERSHIP",title:"Sheldon's Power Statement",author:"Sheldon McClelland",date:"Apr 11",desc:"COO's definitive positioning statement on Baseline Analytics' market authority and competitive moat. Articulates the 'why now' and 'why us' for external-facing communications."},{id:3,type:"MARKET INTEL",title:"Marketplace Comparables Doc",author:"Sheldon McClelland",date:"Apr 8",desc:"League-wide sports tech deal comparables — $6B+ in documented transactions across MLB, NBA, NFL. Positions ACIS pricing against BAMTech, Digital Athlete, Second Spectrum."},{id:4,type:"GOVERNANCE",title:"IAB Program Framework Finalized",author:"Jeff Newman",date:"Apr 5",desc:"Advisory Board governance completed — roles, seat terms, honorarium structure, quarterly cadence."},{id:5,type:"BRAND",title:"Brand Guidelines v1.0 Delivered",author:"PERKK Studio",date:"Apr 3",desc:"Full identity system — logo lockups, color palette, typography, brand asset patterns, mockups."},{id:6,type:"PARTNERSHIP",title:"TrackMan Integration Pathway",author:"Chase Spivey",date:"Mar 30",desc:"Technical alignment confirmed with TrackMan for data feed integration within ACIS."}];
const DOCS=[{name:"Sports Tech Deal Comparables",ext:"PDF",pages:"5 pg",date:"Mar '26",cat:"Intel"},{name:"IAB Overview & Governance",ext:"PDF",pages:"3 pg",date:"Mar '26",cat:"Gov"},{name:"Brand Guidelines v1.0",ext:"PDF",pages:"42 pg",date:"Jan '26",cat:"Brand"},{name:"Hayden Birdsong Case Study",ext:"DOC",pages:"Draft",date:"Apr '26",cat:"Case"},{name:"Investor Deck — Q1 2026",ext:"PPTX",pages:"18 sl",date:"Apr '26",cat:"Deck"},{name:"Power Statement — McClelland",ext:"DOC",pages:"1 pg",date:"Apr '26",cat:"Lead"}];
const QS=["How many investor meetings this month?","Latest on IAB onboarding?","Summarize the Birdsong case study","Deal comparables overview","Materials created this cycle?","Next advisory board call?"];
const ANS={"How many investor meetings this month?":"4 investor meetings in April 2026 — Mark Shirman (BizAnalytica), Scott Price (Beacon Oral), Kris Withrow (Fenwick & West), and Tom Castillo follow-up.","Latest on IAB onboarding?":"Framework finalized. Two April discovery calls — Edwin Prather and Stephen Piscotty. Both expressed strong interest.","Summarize the Birdsong case study":"Analysis of SF Giants pitcher Birdsong's biomechanical markers through ACIS. Demonstrates real-world predictive injury detection using MLB data. Cornerstone proof-of-concept.","Deal comparables overview":"7 deals totaling $6B+. NFL Digital Athlete ($60M+), Second Spectrum + NBA (~$42M/yr), Sportradar + MLB ($37M equity + annual). ACIS range: $15–50M/yr.","Materials created this cycle?":"Birdsong Case Study (Chase), Power Statement (Sheldon), Comparables Doc (Sheldon), IAB Framework (Jeff), Brand Guidelines (PERKK), TrackMan memo (Chase).","Next advisory board call?":"No date confirmed. IAB set for 4 quarterly meetings/year. Next window: late April / early May 2026."};
const CTX=`You are the Baseline Analytics Stakeholder Portal assistant. 2-3 sentences, use names/dates/numbers.\nMEETINGS: ${MEETINGS.map(m=>`${m.date}: ${m.title}`).join("|")}\nBUZZ: ${BUZZ.map(b=>`${b.date}: ${b.title} by ${b.author}`).join("|")}\nKEY: CEO Chase Spivey, COO Sheldon McClelland, Chairman Jeff Newman. ACIS=AI injury prevention for MLB. Comps: $6B+, ACIS $15-50M/yr.`;
const CY="Mar 24 – Apr 23, 2026";

function Logo({s=22}){return <svg width={s*.7} height={s} viewBox="0 0 28 38" fill="none"><rect x="1" y="1" width="2" height="26" rx="1" fill={C.t4}/><rect x="6" y="5" width="2" height="22" rx="1" fill={C.gold}/><rect x="11" y="0" width="2" height="30" rx="1" fill={C.gold}/><rect x="16" y="6" width="2" height="20" rx="1" fill={C.gold}/><rect x="21" y="3" width="2" height="24" rx="1" fill={C.t4}/><path d="M12 30 L7 38 L17 38 Z" fill={C.gold} opacity="0.25"/></svg>}
function Tag({label,color}){return <span style={{display:"inline-block",padding:"3px 8px",borderRadius:4,background:`${color}12`,color,fontSize:9,fontWeight:700,letterSpacing:"0.1em",textTransform:"uppercase",fontFamily:"'DM Mono',monospace"}}>{label}</span>}

export default function V3(){
  const[nav,setNav]=useState("overview");const[filter,setFilter]=useState("ALL");const[exp,setExp]=useState(null);const[q,setQ]=useState("");const[a,setA]=useState("");const[loading,setLoading]=useState(false);const[input,setInput]=useState("");const[hist,setHist]=useState([]);const[fade,setFade]=useState(false);
  useEffect(()=>{setTimeout(()=>setFade(true),50)},[]);
  const fm=filter==="ALL"?MEETINGS:MEETINGS.filter(m=>m.type===filter);
  const ask=async(question)=>{setQ(question);setA("");setLoading(true);const msgs=[...hist,{role:"user",content:question}];if(ANS[question]){setA(ANS[question]);setHist([...msgs,{role:"assistant",content:ANS[question]}]);setLoading(false);return}try{const r=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:"claude-sonnet-4-20250514",max_tokens:1000,system:CTX,messages:msgs.slice(-6)})});const d=await r.json();const ans=d.content?.map(b=>b.type==="text"?b.text:"").filter(Boolean).join("\n")||"No response.";setA(ans);setHist([...msgs,{role:"assistant",content:ans}])}catch{setA("Connection error.")}setLoading(false)};
  const submit=()=>{if(input.trim()){ask(input.trim());setInput("")}};
  return(
    <div style={{fontFamily:"'Source Serif 4',Georgia,serif",background:C.bg,minHeight:"100vh",color:C.text,opacity:fade?1:0,transition:"opacity 0.5s ease"}}>
      <link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:opsz,wght@8..60,200;8..60,300;8..60,400;8..60,600;8..60,700&family=DM+Sans:wght@300;400;500;600;700&family=DM+Mono:wght@300;400;500&display=swap" rel="stylesheet"/>
      <style>{`*{box-sizing:border-box;margin:0}::selection{background:${C.goldL}}@keyframes fadeIn{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:translateY(0)}}@keyframes pulse{0%,100%{opacity:.3}50%{opacity:1}}`}</style>
      {/* NAV */}
      <header style={{background:C.white,borderBottom:`1px solid ${C.border}`,position:"sticky",top:0,zIndex:100}}><div style={{maxWidth:1100,margin:"0 auto",padding:"0 32px",display:"flex",alignItems:"center",justifyContent:"space-between",height:60}}>
        <div style={{display:"flex",alignItems:"center",gap:10}}><Logo s={24}/><span style={{fontSize:13,fontWeight:700,letterSpacing:"0.1em",textTransform:"uppercase",fontFamily:"'DM Sans',sans-serif"}}>Baseline <span style={{fontWeight:400,color:C.t3}}>Analytics</span></span></div>
        <nav style={{display:"flex",gap:0,height:60}}>{["overview","buzz","meetings","vault","ask"].map(n=><button key={n} onClick={()=>setNav(n)} style={{background:"none",border:"none",borderBottom:nav===n?`2px solid ${C.gold}`:"2px solid transparent",color:nav===n?C.text:C.t3,padding:"0 18px",height:"100%",fontSize:13,fontWeight:nav===n?600:400,cursor:"pointer",fontFamily:"'DM Sans',sans-serif",textTransform:"capitalize"}}>{n}</button>)}</nav>
        <div style={{fontSize:10,color:C.t3,fontFamily:"'DM Mono',monospace"}}>{CY}</div>
      </div></header>
      <div style={{maxWidth:1100,margin:"0 auto",padding:"32px 32px 80px"}}>
        {/* OVERVIEW */}
        {nav==="overview"&&<div style={{animation:"fadeIn 0.4s ease"}}>
          <div style={{marginBottom:32}}><h1 style={{fontSize:38,fontWeight:300,letterSpacing:"-0.02em",lineHeight:1.2}}>Stakeholder Portal</h1><div style={{width:40,height:3,background:C.gold,borderRadius:2,marginTop:12}}/></div>
          <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:16,marginBottom:36}}>{[{n:MEETINGS.length,l:"Meetings"},{n:BUZZ.length,l:"Buzz Items"},{n:DOCS.length,l:"Documents"},{n:"0",l:"Days Left"}].map((s,i)=><div key={i} style={{background:C.white,borderRadius:10,padding:"20px 24px",boxShadow:C.shadow}}><div style={{fontSize:36,fontWeight:700,color:C.gold,fontFamily:"'DM Mono',monospace",lineHeight:1}}>{s.n}</div><div style={{fontSize:11,color:C.t3,marginTop:6,fontFamily:"'DM Sans',sans-serif",fontWeight:500,letterSpacing:"0.04em",textTransform:"uppercase"}}>{s.l}</div></div>)}</div>
          {/* Buzz */}
          <div style={{marginBottom:36}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><h2 style={{fontSize:20,fontWeight:600,fontFamily:"'DM Sans',sans-serif"}}>Recent Buzz</h2><button onClick={()=>setNav("buzz")} style={{background:"none",border:"none",color:C.gold,fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>View all →</button></div>
            <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:16}}>{BUZZ.slice(0,3).map(b=><div key={b.id} onClick={()=>setExp(exp===b.id?null:b.id)} style={{background:C.white,borderRadius:10,padding:22,boxShadow:C.shadow,cursor:"pointer",transition:"box-shadow 0.25s",borderLeft:`3px solid ${TC[b.type]}`}} onMouseEnter={e=>e.currentTarget.style.boxShadow=C.shadowH} onMouseLeave={e=>e.currentTarget.style.boxShadow=C.shadow}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><Tag label={b.type} color={TC[b.type]}/><span style={{fontSize:11,color:C.t3,fontFamily:"'DM Mono',monospace"}}>{b.date}</span></div><div style={{fontSize:16,fontWeight:600,marginBottom:4,lineHeight:1.3,fontFamily:"'DM Sans',sans-serif"}}>{b.title}</div><div style={{fontSize:11,color:C.t3,fontFamily:"'DM Sans',sans-serif",marginBottom:8}}>{b.author}</div>{exp===b.id&&<p style={{fontSize:13,color:C.t2,lineHeight:1.7,fontFamily:"'DM Sans',sans-serif"}}>{b.desc}</p>}</div>)}</div>
          </div>
          {/* Meetings */}
          <div style={{marginBottom:36}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><h2 style={{fontSize:20,fontWeight:600,fontFamily:"'DM Sans',sans-serif"}}>Recent Meetings</h2><button onClick={()=>setNav("meetings")} style={{background:"none",border:"none",color:C.gold,fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>View all →</button></div>
            <div style={{background:C.white,borderRadius:10,boxShadow:C.shadow,overflow:"hidden"}}>{MEETINGS.slice(0,5).map((m,i)=><div key={m.id} style={{display:"flex",alignItems:"center",gap:16,padding:"14px 22px",borderBottom:i<4?`1px solid ${C.border}`:"none"}}><span style={{fontSize:11,color:C.t3,fontFamily:"'DM Mono',monospace",minWidth:48}}>{m.date}</span><Tag label={m.type} color={TC[m.type]}/><span style={{flex:1,fontSize:14,fontWeight:500,fontFamily:"'DM Sans',sans-serif"}}>{m.title}</span><span style={{fontSize:11,color:C.t3,fontFamily:"'DM Sans',sans-serif"}}>{m.org}</span></div>)}</div>
          </div>
          {/* Ask bar */}
          <div style={{background:C.white,borderRadius:10,boxShadow:C.shadow,padding:"18px 22px",display:"flex",alignItems:"center",gap:12}}><div style={{fontSize:11,fontWeight:700,color:C.gold,fontFamily:"'DM Sans',sans-serif",letterSpacing:"0.08em",flexShrink:0}}>ASK</div><input type="text" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){setNav("ask");submit()}}} placeholder="Type a question..." style={{flex:1,padding:"8px 0",background:"none",border:"none",color:C.text,fontSize:14,fontFamily:"'DM Sans',sans-serif",outline:"none"}}/><button onClick={()=>{setNav("ask");submit()}} style={{background:C.gold,border:"none",color:C.white,width:36,height:36,borderRadius:8,fontSize:16,cursor:"pointer",fontWeight:700,display:"flex",alignItems:"center",justifyContent:"center"}}>→</button></div>
        </div>}
        {/* BUZZ */}
        {nav==="buzz"&&<div style={{animation:"fadeIn 0.4s ease"}}><div style={{marginBottom:28}}><h1 style={{fontSize:32,fontWeight:300}}>Recent Buzz</h1><div style={{width:32,height:3,background:C.gold,borderRadius:2,marginTop:10}}/><p style={{fontSize:12,color:C.t3,marginTop:10,fontFamily:"'DM Sans',sans-serif"}}>{CY} — All items reset on cycle end.</p></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:18}}>{BUZZ.map(b=><div key={b.id} onClick={()=>setExp(exp===b.id?null:b.id)} style={{background:C.white,borderRadius:10,padding:24,boxShadow:C.shadow,cursor:"pointer",transition:"box-shadow 0.25s",borderLeft:`3px solid ${TC[b.type]}`}} onMouseEnter={e=>e.currentTarget.style.boxShadow=C.shadowH} onMouseLeave={e=>e.currentTarget.style.boxShadow=C.shadow}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><Tag label={b.type} color={TC[b.type]}/><span style={{fontSize:11,color:C.t3,fontFamily:"'DM Mono',monospace"}}>{b.date}</span></div><div style={{fontSize:18,fontWeight:600,marginBottom:4,lineHeight:1.3,fontFamily:"'DM Sans',sans-serif"}}>{b.title}</div><div style={{fontSize:12,color:C.t3,fontFamily:"'DM Sans',sans-serif",marginBottom:exp===b.id?12:0}}>{b.author}</div>{exp===b.id&&<p style={{fontSize:14,color:C.t2,lineHeight:1.75,fontFamily:"'DM Sans',sans-serif"}}>{b.desc}</p>}</div>)}</div></div>}
        {/* MEETINGS */}
        {nav==="meetings"&&<div style={{animation:"fadeIn 0.4s ease"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",marginBottom:24}}><div><h1 style={{fontSize:32,fontWeight:300}}>Meetings</h1><div style={{width:32,height:3,background:C.gold,borderRadius:2,marginTop:10}}/></div><div style={{display:"flex",gap:4}}>{["ALL","INVESTOR","ADVISORY","STRATEGY"].map(f=><button key={f} onClick={()=>setFilter(f)} style={{background:filter===f?C.goldBg:C.white,border:`1px solid ${filter===f?C.gold+"40":C.border}`,color:filter===f?C.goldD:C.t3,padding:"5px 12px",borderRadius:6,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:"'DM Mono',monospace"}}>{f}</button>)}</div></div>
          <div style={{background:C.white,borderRadius:10,boxShadow:C.shadow,overflow:"hidden"}}><div style={{display:"grid",gridTemplateColumns:"60px 90px 1fr 90px",gap:16,padding:"10px 22px",borderBottom:`1px solid ${C.borderS}`}}>{["Date","Type","Meeting","Org"].map(h=><span key={h} style={{fontSize:9,fontWeight:700,color:C.t3,letterSpacing:"0.12em",textTransform:"uppercase",fontFamily:"'DM Mono',monospace"}}>{h}</span>)}</div>{fm.map((m,i)=><div key={m.id} style={{display:"grid",gridTemplateColumns:"60px 90px 1fr 90px",gap:16,padding:"14px 22px",borderBottom:i<fm.length-1?`1px solid ${C.border}`:"none",transition:"background 0.15s"}} onMouseEnter={e=>e.currentTarget.style.background=C.surface} onMouseLeave={e=>e.currentTarget.style.background="transparent"}><span style={{fontSize:12,color:C.t3,fontFamily:"'DM Mono',monospace"}}>{m.date}</span><Tag label={m.type} color={TC[m.type]}/><div><div style={{fontSize:14,fontWeight:500,fontFamily:"'DM Sans',sans-serif",marginBottom:2}}>{m.title}</div><div style={{fontSize:12,color:C.t3,fontFamily:"'DM Sans',sans-serif",lineHeight:1.5}}>{m.summary}</div></div><span style={{fontSize:12,color:C.t2,fontFamily:"'DM Sans',sans-serif"}}>{m.org}</span></div>)}</div>
        </div>}
        {/* VAULT */}
        {nav==="vault"&&<div style={{animation:"fadeIn 0.4s ease"}}><div style={{marginBottom:24}}><h1 style={{fontSize:32,fontWeight:300}}>Documents</h1><div style={{width:32,height:3,background:C.gold,borderRadius:2,marginTop:10}}/></div><div style={{background:C.white,borderRadius:10,boxShadow:C.shadow,overflow:"hidden"}}><div style={{display:"grid",gridTemplateColumns:"50px 1fr 60px 70px 60px",gap:16,padding:"10px 22px",borderBottom:`1px solid ${C.borderS}`}}>{["Ext","Document","Size","Date",""].map(h=><span key={h} style={{fontSize:9,fontWeight:700,color:C.t3,letterSpacing:"0.12em",textTransform:"uppercase",fontFamily:"'DM Mono',monospace"}}>{h}</span>)}</div>{DOCS.map((d,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"50px 1fr 60px 70px 60px",gap:16,padding:"14px 22px",borderBottom:i<DOCS.length-1?`1px solid ${C.border}`:"none",alignItems:"center",transition:"background 0.15s"}} onMouseEnter={e=>e.currentTarget.style.background=C.surface} onMouseLeave={e=>e.currentTarget.style.background="transparent"}><span style={{fontSize:9,fontWeight:700,color:C.goldD,fontFamily:"'DM Mono',monospace",background:C.goldBg,padding:"3px 6px",borderRadius:4,textAlign:"center"}}>{d.ext}</span><div><div style={{fontSize:14,fontWeight:500,fontFamily:"'DM Sans',sans-serif"}}>{d.name}</div><div style={{fontSize:10,color:C.t3,fontFamily:"'DM Mono',monospace",marginTop:1}}>{d.cat}</div></div><span style={{fontSize:11,color:C.t3,fontFamily:"'DM Mono',monospace"}}>{d.pages}</span><span style={{fontSize:11,color:C.t3,fontFamily:"'DM Mono',monospace"}}>{d.date}</span><button style={{background:C.surface,border:`1px solid ${C.border}`,color:C.t2,padding:"5px 12px",borderRadius:6,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>Open</button></div>)}</div></div>}
        {/* ASK */}
        {nav==="ask"&&<div style={{animation:"fadeIn 0.4s ease"}}><div style={{marginBottom:24}}><h1 style={{fontSize:32,fontWeight:300}}>Ask the Portal</h1><div style={{width:32,height:3,background:C.gold,borderRadius:2,marginTop:10}}/></div>
          <div style={{background:C.white,borderRadius:10,boxShadow:C.shadow,padding:"6px 6px 6px 20px",display:"flex",alignItems:"center",gap:10,marginBottom:20}}><input type="text" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder="Type a question..." style={{flex:1,padding:"12px 0",background:"none",border:"none",color:C.text,fontSize:15,fontFamily:"'DM Sans',sans-serif",outline:"none"}}/><button onClick={submit} disabled={!input.trim()||loading} style={{background:input.trim()?C.gold:C.t4,border:"none",color:input.trim()?C.white:C.t3,padding:"12px 24px",borderRadius:8,fontSize:12,fontWeight:700,cursor:input.trim()?"pointer":"default",fontFamily:"'DM Sans',sans-serif"}}>{loading?"···":"Ask"}</button></div>
          <div style={{display:"flex",flexWrap:"wrap",gap:8,marginBottom:24}}>{QS.map((qu,i)=><button key={i} onClick={()=>ask(qu)} style={{background:q===qu?C.goldBg:C.white,border:`1px solid ${q===qu?C.gold+"40":C.border}`,color:q===qu?C.goldD:C.t2,padding:"8px 16px",borderRadius:8,fontSize:12,cursor:"pointer",fontFamily:"'DM Sans',sans-serif",fontWeight:500,boxShadow:C.shadow}}>{qu}</button>)}</div>
          {loading&&<div style={{display:"flex",alignItems:"center",gap:8,padding:20,color:C.t3,fontSize:13,fontFamily:"'DM Sans',sans-serif"}}><span style={{color:C.gold,animation:"pulse 1s infinite"}}>●</span> Searching...</div>}
          {a&&!loading&&<div style={{background:C.white,borderRadius:10,boxShadow:C.shadow,padding:24,borderLeft:`3px solid ${C.gold}`}}><div style={{fontSize:10,fontWeight:600,color:C.gold,marginBottom:8,fontFamily:"'DM Mono',monospace"}}>↳ {q}</div><p style={{fontSize:15,lineHeight:1.8,fontFamily:"'DM Sans',sans-serif",fontWeight:400,whiteSpace:"pre-wrap"}}>{a}</p></div>}
          {!a&&!loading&&<p style={{fontSize:13,color:C.t3,fontFamily:"'DM Sans',sans-serif",fontStyle:"italic"}}>Select a question or type your own above.</p>}
        </div>}
      </div>
      <footer style={{borderTop:`1px solid ${C.border}`,padding:"16px 32px",maxWidth:1100,margin:"0 auto",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:8}}><Logo s={16}/><span style={{fontSize:10,color:C.t3,fontFamily:"'DM Sans',sans-serif"}}>Baseline Analytics™ · Confidential</span></div><span style={{fontSize:10,color:C.t4,fontFamily:"'DM Mono',monospace"}}>baselineanalytics.net</span></footer>
    </div>
  );
}
