import { useState, useEffect } from "react";

const C = { bg:"#060605", panel:"#0C0C0B", card:"#111110", cardH:"#181816", rule:"rgba(255,198,85,0.08)", ruleS:"rgba(255,198,85,0.18)", gold:"#FFC655", goldD:"#D4A548", goldM:"#8A7342", t1:"#F0EDE6", t2:"rgba(240,237,230,0.50)", t3:"rgba(240,237,230,0.22)", black:"#000000" };
const TC = { INVESTOR:"#4ADE80", ADVISORY:"#FF6B6B", STRATEGY:"#FB923C", "CASE STUDY":"#FFC655", LEADERSHIP:"#A78BFA", "MARKET INTEL":"#4ADE80", GOVERNANCE:"#60A5FA", BRAND:"#FB923C", PARTNERSHIP:"#22D3EE" };
const MEETINGS=[{id:1,type:"INVESTOR",date:"Apr 9",title:"Mark Shirman Investor Discovery Call",summary:"Discovery call with Mark Shirman, former CEO of RiverMeadow Software (connection via Jeff Newman). Strong investment interest expressed.",org:"BizAnalytica"},{id:2,type:"INVESTOR",date:"Apr 7",title:"Scott Price Investor Discovery Call",summary:"Discovery call with Scott Price, President at Beacon Oral Specialists (via Tom Castillo). Personal investment interest discussed.",org:"Beacon Oral"},{id:3,type:"ADVISORY",date:"Apr 2",title:"Edwin Prather IAB Discovery Call",summary:"Discovery call with Edwin Prather, Bay Area attorney and General Counsel at Alexander's Steakhouse.",org:"Prather"},{id:4,type:"INVESTOR",date:"Apr 2",title:"Kris Withrow — Fenwick & West",summary:"Strategic legal framework and investor introduction opportunities.",org:"Fenwick"},{id:5,type:"STRATEGY",date:"Apr 2",title:"TrackMan Momentum Call — Adam Katz",summary:"Integration possibilities and data partnership alignment for the platform.",org:"TrackMan"},{id:6,type:"ADVISORY",date:"Apr 2",title:"Stephen Piscotty IAB Discovery Call",summary:"IAB candidacy — former MLB experience and player development connections.",org:"Piscotty"},{id:7,type:"INVESTOR",date:"Mar 28",title:"Tom Castillo Follow-Up",summary:"Investment terms, timeline, and next steps for formalizing commitment.",org:"Castillo"},{id:8,type:"STRATEGY",date:"Mar 25",title:"ACIS Positioning Review",summary:"ACIS positioning vs. NFL Digital Athlete and NBA Second Spectrum comparables.",org:"Internal"}];
const BUZZ=[{id:1,type:"CASE STUDY",title:"Hayden Birdsong Case Study",author:"Chase Spivey",date:"Apr 14",desc:"Deep-dive on SF Giants pitcher Hayden Birdsong's biomechanical markers through the ACIS lens. Demonstrates predictive injury detection with real MLB data — cornerstone proof-of-concept for investor conversations."},{id:2,type:"LEADERSHIP",title:"Sheldon's Power Statement",author:"Sheldon McClelland",date:"Apr 11",desc:"COO's definitive positioning statement on Baseline Analytics' market authority and competitive moat. Articulates the 'why now' and 'why us' for external-facing communications."},{id:3,type:"MARKET INTEL",title:"Marketplace Comparables Doc",author:"Sheldon McClelland",date:"Apr 8",desc:"League-wide sports tech deal comparables — $6B+ in documented transactions across MLB, NBA, NFL. Positions ACIS pricing against BAMTech, Digital Athlete, Second Spectrum."},{id:4,type:"GOVERNANCE",title:"IAB Program Framework Finalized",author:"Jeff Newman",date:"Apr 5",desc:"Advisory Board governance completed — roles, seat terms, honorarium structure, quarterly cadence."},{id:5,type:"BRAND",title:"Brand Guidelines v1.0 Delivered",author:"PERKK Studio",date:"Apr 3",desc:"Full identity system — logo lockups, color palette, typography, brand asset patterns, mockups."},{id:6,type:"PARTNERSHIP",title:"TrackMan Integration Pathway",author:"Chase Spivey",date:"Mar 30",desc:"Technical alignment confirmed with TrackMan for data feed integration within ACIS."}];
const DOCS=[{name:"Sports Tech Deal Comparables",ext:"PDF",pages:"5 pg",date:"Mar '26",cat:"Intel"},{name:"IAB Overview & Governance",ext:"PDF",pages:"3 pg",date:"Mar '26",cat:"Gov"},{name:"Brand Guidelines v1.0",ext:"PDF",pages:"42 pg",date:"Jan '26",cat:"Brand"},{name:"Hayden Birdsong Case Study",ext:"DOC",pages:"Draft",date:"Apr '26",cat:"Case"},{name:"Investor Deck — Q1 2026",ext:"PPTX",pages:"18 sl",date:"Apr '26",cat:"Deck"},{name:"Power Statement — McClelland",ext:"DOC",pages:"1 pg",date:"Apr '26",cat:"Lead"}];
const QS=["How many investor meetings this month?","Latest on IAB onboarding?","Summarize the Birdsong case study","Deal comparables overview","Materials created this cycle?","Next advisory board call?"];
const ANS={"How many investor meetings this month?":"4 investor meetings in April 2026 — Mark Shirman (BizAnalytica), Scott Price (Beacon Oral), Kris Withrow (Fenwick & West), and Tom Castillo follow-up.","Latest on IAB onboarding?":"Framework finalized. Two April discovery calls — Edwin Prather and Stephen Piscotty. Both expressed strong interest.","Summarize the Birdsong case study":"Analysis of SF Giants pitcher Birdsong's biomechanical markers through ACIS. Demonstrates real-world predictive injury detection using MLB data. Cornerstone proof-of-concept.","Deal comparables overview":"7 deals totaling $6B+. NFL Digital Athlete ($60M+), Second Spectrum + NBA (~$42M/yr), Sportradar + MLB ($37M equity + annual). ACIS range: $15–50M/yr.","Materials created this cycle?":"Birdsong Case Study (Chase), Power Statement (Sheldon), Comparables Doc (Sheldon), IAB Framework (Jeff), Brand Guidelines (PERKK), TrackMan memo (Chase).","Next advisory board call?":"No date confirmed. IAB set for 4 quarterly meetings/year. Next window: late April / early May 2026."};
const CTX=`You are the Baseline Analytics Stakeholder Portal assistant. 2-3 sentences, use names/dates/numbers.\nMEETINGS: ${MEETINGS.map(m=>`${m.date}: ${m.title}`).join("|")}\nBUZZ: ${BUZZ.map(b=>`${b.date}: ${b.title} by ${b.author}`).join("|")}\nKEY: CEO Chase Spivey, COO Sheldon McClelland, Chairman Jeff Newman. ACIS=AI injury prevention for MLB. Comps: $6B+, ACIS $15-50M/yr.`;
const CY="Mar 24 – Apr 23, 2026";

function Logo({s=24}){return <svg width={s*.7} height={s} viewBox="0 0 28 38" fill="none"><rect x="1" y="1" width="2" height="26" rx="1" fill={C.goldM}/><rect x="6" y="5" width="2" height="22" rx="1" fill={C.gold}/><rect x="11" y="0" width="2" height="30" rx="1" fill={C.gold}/><rect x="16" y="6" width="2" height="20" rx="1" fill={C.gold}/><rect x="21" y="3" width="2" height="24" rx="1" fill={C.goldM}/><path d="M12 30 L7 38 L17 38 Z" fill={C.goldD} opacity="0.35"/></svg>}
function Pill({label,color,small}){return <span style={{display:"inline-block",padding:small?"2px 7px":"3px 9px",borderRadius:3,background:`${color}10`,border:`1px solid ${color}20`,fontSize:small?8:9,fontWeight:700,letterSpacing:"0.1em",color,textTransform:"uppercase",fontFamily:"'JetBrains Mono',monospace"}}>{label}</span>}
function Rule({style}){return <div style={{height:1,background:C.rule,...style}}/>}

export default function V2(){
  const[nav,setNav]=useState("overview");const[filter,setFilter]=useState("ALL");const[exp,setExp]=useState(null);const[q,setQ]=useState("");const[a,setA]=useState("");const[loading,setLoading]=useState(false);const[input,setInput]=useState("");const[hist,setHist]=useState([]);const[fade,setFade]=useState(false);
  useEffect(()=>{setTimeout(()=>setFade(true),60)},[]);
  const fm=filter==="ALL"?MEETINGS:MEETINGS.filter(m=>m.type===filter);
  const ask=async(question)=>{setQ(question);setA("");setLoading(true);const msgs=[...hist,{role:"user",content:question}];if(ANS[question]){setA(ANS[question]);setHist([...msgs,{role:"assistant",content:ANS[question]}]);setLoading(false);return}try{const r=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:"claude-sonnet-4-20250514",max_tokens:1000,system:CTX,messages:msgs.slice(-6)})});const d=await r.json();const ans=d.content?.map(b=>b.type==="text"?b.text:"").filter(Boolean).join("\n")||"No response.";setA(ans);setHist([...msgs,{role:"assistant",content:ans}])}catch{setA("Connection error.")}setLoading(false)};
  const submit=()=>{if(input.trim()){ask(input.trim());setInput("")}};
  const navItems=[{key:"overview",label:"Overview",icon:"◈"},{key:"buzz",label:"Buzz",icon:"◆"},{key:"meetings",label:"Meetings",icon:"▤"},{key:"vault",label:"Vault",icon:"▧"},{key:"ask",label:"Ask",icon:"▸"}];
  return(
    <div style={{fontFamily:"'Manrope',sans-serif",background:C.bg,minHeight:"100vh",color:C.t1,opacity:fade?1:0,transition:"opacity 0.6s ease",display:"flex"}}>
      <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&family=JetBrains+Mono:wght@300;400;500;600&display=swap" rel="stylesheet"/>
      <style>{`*{box-sizing:border-box;margin:0}::-webkit-scrollbar{width:4px}::-webkit-scrollbar-thumb{background:${C.gold}20;border-radius:2px}@keyframes fadeUp{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}@keyframes blink{0%,100%{opacity:.2}50%{opacity:1}}`}</style>
      {/* SIDEBAR */}
      <aside style={{width:220,minHeight:"100vh",background:C.panel,borderRight:`1px solid ${C.rule}`,padding:"24px 0",display:"flex",flexDirection:"column",position:"sticky",top:0,flexShrink:0}}>
        <div style={{padding:"0 20px 24px",display:"flex",alignItems:"center",gap:10}}><Logo s={28}/><div><div style={{fontSize:11,fontWeight:800,letterSpacing:"0.14em",textTransform:"uppercase"}}>Baseline</div><div style={{fontSize:9,color:C.t3}}>Analytics™</div></div></div><Rule/>
        <nav style={{padding:"16px 12px",flex:1}}>{navItems.map(n=><button key={n.key} onClick={()=>setNav(n.key)} style={{display:"flex",alignItems:"center",gap:10,width:"100%",padding:"10px 12px",borderRadius:6,border:"none",cursor:"pointer",fontFamily:"inherit",fontSize:13,fontWeight:nav===n.key?600:400,color:nav===n.key?C.gold:C.t2,background:nav===n.key?`${C.gold}08`:"transparent",textAlign:"left",marginBottom:2}}><span style={{fontSize:11,opacity:nav===n.key?1:.4,fontFamily:"monospace"}}>{n.icon}</span>{n.label}</button>)}</nav>
        <div style={{padding:"0 20px"}}><Rule style={{marginBottom:16}}/><div style={{fontSize:8,fontWeight:700,letterSpacing:"0.14em",color:C.t3,textTransform:"uppercase",marginBottom:6}}>Current Cycle</div><div style={{fontSize:10,color:C.goldM,fontFamily:"'JetBrains Mono',monospace",lineHeight:1.6}}>{CY}</div><div style={{fontSize:9,color:C.t3,marginTop:8}}>Updated Apr 23, 2026</div></div>
      </aside>
      {/* MAIN */}
      <main style={{flex:1,minHeight:"100vh",overflow:"auto"}}>
        {/* OVERVIEW */}
        {nav==="overview"&&<div style={{animation:"fadeUp 0.4s ease"}}>
          <div style={{padding:"28px 36px 20px",borderBottom:`1px solid ${C.rule}`}}><div style={{fontSize:9,fontWeight:700,letterSpacing:"0.16em",color:C.t3,textTransform:"uppercase",marginBottom:6}}>Stakeholder Portal</div><div style={{fontSize:28,fontWeight:300}}>Overview<span style={{color:C.gold}}>.</span></div></div>
          <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",borderBottom:`1px solid ${C.rule}`}}>{[{l:"Meetings",v:MEETINGS.length},{l:"Buzz Items",v:BUZZ.length},{l:"Documents",v:DOCS.length},{l:"Cycle Days Left",v:"0"}].map((s,i)=><div key={i} style={{padding:"20px 36px",borderRight:i<3?`1px solid ${C.rule}`:"none"}}><div style={{fontSize:32,fontWeight:700,color:C.gold,fontFamily:"'JetBrains Mono',monospace"}}>{s.v}</div><div style={{fontSize:10,color:C.t3,letterSpacing:"0.08em",textTransform:"uppercase",marginTop:2,fontWeight:600}}>{s.l}</div></div>)}</div>
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr"}}>
            <div style={{borderRight:`1px solid ${C.rule}`,padding:"24px 36px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:18}}><div style={{fontSize:9,fontWeight:700,letterSpacing:"0.14em",color:C.gold,textTransform:"uppercase"}}>Recent Buzz</div><button onClick={()=>setNav("buzz")} style={{background:"none",border:"none",color:C.t3,fontSize:10,cursor:"pointer",fontFamily:"inherit"}}>View all →</button></div>{BUZZ.slice(0,4).map((b,i)=><div key={b.id}><div style={{padding:"14px 0",cursor:"pointer"}} onClick={()=>setExp(exp===b.id?null:b.id)}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><Pill label={b.type} color={TC[b.type]} small/><span style={{fontSize:10,color:C.t3,fontFamily:"'JetBrains Mono',monospace"}}>{b.date}</span></div><div style={{fontSize:14,fontWeight:600,marginBottom:3}}>{b.title}</div><div style={{fontSize:11,color:C.t3}}>{b.author}</div>{exp===b.id&&<p style={{fontSize:12,color:C.t2,lineHeight:1.7,marginTop:8,borderLeft:`2px solid ${C.gold}30`,paddingLeft:12}}>{b.desc}</p>}</div>{i<3&&<Rule/>}</div>)}</div>
            <div style={{padding:"24px 36px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:18}}><div style={{fontSize:9,fontWeight:700,letterSpacing:"0.14em",color:C.gold,textTransform:"uppercase"}}>Recent Meetings</div><button onClick={()=>setNav("meetings")} style={{background:"none",border:"none",color:C.t3,fontSize:10,cursor:"pointer",fontFamily:"inherit"}}>View all →</button></div>{MEETINGS.slice(0,5).map((m,i)=><div key={m.id}><div style={{padding:"12px 0",display:"flex",gap:14,alignItems:"flex-start"}}><div style={{fontSize:11,fontWeight:600,color:C.t3,fontFamily:"'JetBrains Mono',monospace",minWidth:48,paddingTop:2}}>{m.date}</div><div style={{flex:1}}><div style={{fontSize:13,fontWeight:600,marginBottom:4,lineHeight:1.3}}>{m.title}</div><div style={{display:"flex",gap:8,alignItems:"center"}}><Pill label={m.type} color={TC[m.type]} small/><span style={{fontSize:10,color:C.t3}}>{m.org}</span></div></div></div>{i<4&&<Rule/>}</div>)}</div>
          </div>
          <div style={{borderTop:`1px solid ${C.rule}`,padding:"20px 36px",display:"flex",alignItems:"center",gap:12}}><span style={{fontSize:9,fontWeight:700,letterSpacing:"0.12em",color:C.gold,flexShrink:0}}>ASK</span><input type="text" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){setNav("ask");submit()}}} placeholder="Type a question..." style={{flex:1,padding:"10px 16px",background:C.card,border:`1px solid ${C.rule}`,borderRadius:4,color:C.t1,fontSize:13,fontFamily:"inherit",outline:"none"}} onFocus={e=>e.target.style.borderColor=`${C.gold}40`} onBlur={e=>e.target.style.borderColor=C.rule}/><button onClick={()=>{setNav("ask");submit()}} style={{background:C.gold,border:"none",color:C.black,padding:"10px 20px",borderRadius:4,fontSize:11,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>→</button></div>
        </div>}
        {/* BUZZ */}
        {nav==="buzz"&&<div style={{animation:"fadeUp 0.4s ease"}}><div style={{padding:"28px 36px 20px",borderBottom:`1px solid ${C.rule}`}}><div style={{fontSize:9,fontWeight:700,letterSpacing:"0.16em",color:C.t3,textTransform:"uppercase",marginBottom:6}}>30-Day Cycle</div><div style={{fontSize:28,fontWeight:300}}>Recent Buzz<span style={{color:C.gold}}>.</span></div><div style={{fontSize:11,color:C.t3,marginTop:6,fontFamily:"'JetBrains Mono',monospace"}}>{CY} — All items reset on cycle end.</div></div>{BUZZ.map(b=><div key={b.id} style={{borderBottom:`1px solid ${C.rule}`,cursor:"pointer"}} onClick={()=>setExp(exp===b.id?null:b.id)}><div style={{padding:"20px 36px",display:"grid",gridTemplateColumns:"80px 120px 1fr auto",gap:20,alignItems:"start"}}><div style={{fontSize:12,color:C.t3,fontFamily:"'JetBrains Mono',monospace"}}>{b.date}</div><Pill label={b.type} color={TC[b.type]}/><div><div style={{fontSize:15,fontWeight:600,marginBottom:3}}>{b.title}</div><div style={{fontSize:11,color:C.t3}}>{b.author}</div>{exp===b.id&&<p style={{fontSize:13,color:C.t2,lineHeight:1.75,marginTop:12,maxWidth:560}}>{b.desc}</p>}</div><span style={{fontSize:11,color:C.t3,fontFamily:"monospace"}}>{exp===b.id?"−":"+"}</span></div></div>)}</div>}
        {/* MEETINGS */}
        {nav==="meetings"&&<div style={{animation:"fadeUp 0.4s ease"}}><div style={{padding:"28px 36px 20px",borderBottom:`1px solid ${C.rule}`,display:"flex",justifyContent:"space-between",alignItems:"flex-end"}}><div><div style={{fontSize:9,fontWeight:700,letterSpacing:"0.16em",color:C.t3,textTransform:"uppercase",marginBottom:6}}>Timeline</div><div style={{fontSize:28,fontWeight:300}}>Meetings<span style={{color:C.gold}}>.</span></div></div><div style={{display:"flex",gap:4,paddingBottom:4}}>{["ALL","INVESTOR","ADVISORY","STRATEGY"].map(f=><button key={f} onClick={()=>setFilter(f)} style={{background:filter===f?`${C.gold}12`:"transparent",border:`1px solid ${filter===f?C.gold+"30":C.rule}`,color:filter===f?C.gold:C.t3,padding:"4px 10px",borderRadius:3,fontSize:9,fontWeight:700,cursor:"pointer",fontFamily:"'JetBrains Mono',monospace"}}>{f}</button>)}</div></div>
          <div style={{display:"grid",gridTemplateColumns:"80px 100px 1fr 90px",gap:20,padding:"12px 36px",borderBottom:`1px solid ${C.ruleS}`}}>{["DATE","TYPE","MEETING","ORG"].map(h=><div key={h} style={{fontSize:8,fontWeight:700,letterSpacing:"0.16em",color:C.t3,fontFamily:"'JetBrains Mono',monospace"}}>{h}</div>)}</div>
          {fm.map(m=><div key={m.id} style={{display:"grid",gridTemplateColumns:"80px 100px 1fr 90px",gap:20,padding:"16px 36px",borderBottom:`1px solid ${C.rule}`,transition:"background 0.15s"}} onMouseEnter={e=>e.currentTarget.style.background=C.card} onMouseLeave={e=>e.currentTarget.style.background="transparent"}><div style={{fontSize:12,color:C.t3,fontFamily:"'JetBrains Mono',monospace"}}>{m.date}</div><Pill label={m.type} color={TC[m.type]} small/><div><div style={{fontSize:14,fontWeight:600,marginBottom:3,lineHeight:1.3}}>{m.title}</div><div style={{fontSize:11,color:C.t3,lineHeight:1.5}}>{m.summary}</div></div><div style={{fontSize:11,color:C.t2}}>{m.org}</div></div>)}
        </div>}
        {/* VAULT */}
        {nav==="vault"&&<div style={{animation:"fadeUp 0.4s ease"}}><div style={{padding:"28px 36px 20px",borderBottom:`1px solid ${C.rule}`}}><div style={{fontSize:28,fontWeight:300}}>Vault<span style={{color:C.gold}}>.</span></div></div><div style={{display:"grid",gridTemplateColumns:"60px 60px 1fr 60px 80px 60px",gap:20,padding:"12px 36px",borderBottom:`1px solid ${C.ruleS}`}}>{["EXT","CAT","DOCUMENT","SIZE","DATE",""].map(h=><div key={h} style={{fontSize:8,fontWeight:700,letterSpacing:"0.16em",color:C.t3,fontFamily:"'JetBrains Mono',monospace"}}>{h}</div>)}</div>{DOCS.map((d,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"60px 60px 1fr 60px 80px 60px",gap:20,padding:"14px 36px",borderBottom:`1px solid ${C.rule}`,alignItems:"center"}} onMouseEnter={e=>e.currentTarget.style.background=C.card} onMouseLeave={e=>e.currentTarget.style.background="transparent"}><span style={{fontSize:10,fontWeight:700,color:C.gold,fontFamily:"'JetBrains Mono',monospace",background:`${C.gold}10`,padding:"3px 6px",borderRadius:3,textAlign:"center"}}>{d.ext}</span><span style={{fontSize:9,color:C.t3,fontFamily:"'JetBrains Mono',monospace"}}>{d.cat}</span><span style={{fontSize:14,fontWeight:500}}>{d.name}</span><span style={{fontSize:10,color:C.t3,fontFamily:"'JetBrains Mono',monospace"}}>{d.pages}</span><span style={{fontSize:10,color:C.t3,fontFamily:"'JetBrains Mono',monospace"}}>{d.date}</span><button style={{background:`${C.gold}10`,border:`1px solid ${C.gold}20`,color:C.gold,padding:"4px 10px",borderRadius:3,fontSize:9,fontWeight:700,cursor:"pointer",fontFamily:"'JetBrains Mono',monospace"}}>OPEN</button></div>)}</div>}
        {/* ASK */}
        {nav==="ask"&&<div style={{animation:"fadeUp 0.4s ease"}}><div style={{padding:"28px 36px 20px",borderBottom:`1px solid ${C.rule}`}}><div style={{fontSize:28,fontWeight:300}}>Ask<span style={{color:C.gold}}>.</span></div></div>
          <div style={{padding:"20px 36px",borderBottom:`1px solid ${C.rule}`,display:"flex",gap:10}}><input type="text" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder="Type a question..." style={{flex:1,padding:"12px 16px",background:C.card,border:`1px solid ${C.rule}`,borderRadius:4,color:C.t1,fontSize:14,fontFamily:"inherit",outline:"none"}} onFocus={e=>e.target.style.borderColor=`${C.gold}40`} onBlur={e=>e.target.style.borderColor=C.rule}/><button onClick={submit} disabled={!input.trim()||loading} style={{background:input.trim()?C.gold:`${C.gold}20`,border:"none",color:input.trim()?C.black:C.t3,padding:"12px 24px",borderRadius:4,fontSize:12,fontWeight:700,cursor:input.trim()?"pointer":"default",fontFamily:"inherit"}}>{loading?"···":"ASK"}</button></div>
          <div style={{padding:"16px 36px",borderBottom:`1px solid ${C.rule}`,display:"flex",flexWrap:"wrap",gap:6}}>{QS.map((qu,i)=><button key={i} onClick={()=>ask(qu)} style={{background:q===qu?`${C.gold}10`:C.card,border:`1px solid ${q===qu?C.gold+"30":C.rule}`,color:q===qu?C.gold:C.t2,padding:"7px 14px",borderRadius:3,fontSize:11,cursor:"pointer",fontFamily:"inherit",fontWeight:500}}>{qu}</button>)}</div>
          <div style={{padding:"24px 36px"}}>{loading&&<div style={{display:"flex",alignItems:"center",gap:8,color:C.t3,fontSize:12}}><span style={{color:C.gold,animation:"blink 1s infinite"}}>●</span> Searching...</div>}{a&&!loading&&<div><div style={{fontSize:9,fontWeight:700,letterSpacing:"0.12em",color:C.gold,textTransform:"uppercase",marginBottom:10,fontFamily:"'JetBrains Mono',monospace"}}>↳ {q}</div><p style={{fontSize:15,lineHeight:1.85,fontWeight:300,maxWidth:640,whiteSpace:"pre-wrap"}}>{a}</p></div>}{!a&&!loading&&<div style={{fontSize:13,color:C.t3,fontStyle:"italic"}}>Select a question or type your own above.</div>}</div>
        </div>}
      </main>
    </div>
  );
}
